version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch
      - image: wurstmeister/zookeeper
        name: zookeeper
      - image: wurstmeister/kafka:2.12-2.1.0
        name: kafka
        environment:
          KAFKA_ADVERTISED_HOST_NAME: kafka
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_DELETE_TOPIC_ENABLE: true

    steps:
      - checkout

      - run:
          # circleci support page:
          # https://support.circleci.com/hc/en-us/articles/360006773953-Race-Conditions-Wait-For-Database
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

      - run:
          name: Wait for kafka
          command: dockerize -wait tcp://kafka:9092 -timeout 1m


      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .[kafka]
            python component-tests/kafka/publisher.py
